# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Time Tracker
    description:  Time Tracker
    keywords:     project, time, tracker, manager
    language:     fr
    robots:       index, follow

  has_layout:     true
  layout:         layout
