generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Task
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        table_method: retrieveTaskList
      filter:
        display: [ milestone_id, module_id, name, priority_id ]
      form:    ~
      edit:    ~
      new:     ~
