<?php

/**
 * Input
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    TimeTracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Input extends BaseInput
{
  public function construct()
  {
    parent::construct();
    sfProjectConfiguration::getActive()->loadHelpers('InputTime');
  }

  public function getTimeSpent()
  {
    return $this->isNew() ? $this->_get('time_spent') : format_time($this->_get('time_spent'));
  }

  public function getTimeLeft()
  {
    return $this->isNew() ? $this->_get('time_left') : format_time($this->_get('time_left'));
  }
}
