<?php

/**
 * Milestone
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    TimeTracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Milestone extends BaseMilestone
{
  public function getProfilesCosts()
  {
    return MilestoneProfileTable::getMilestoneProfilesCosts($this->getId());
  }
}
