<?php

/**
 * Project
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    TimeTracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Project extends BaseProject
{
  public function __toString()
  {
    return $this->getCode() . ' - ' . $this->getName();
  }

  public function getUserAssignments(sfGuardUser $user, $withTimeSpent = true, $isCompleted = false)
  {
    return $this->getTable()->getProjectUserAssignments($this->getId(), $user->getId(), $withTimeSpent, $isCompleted);
  }

  public function getOverview($filters = array())
  {
    return $this->getTable()->getProjectOverview($this->getId(), $filters);
  }

  public function getReport($filters = array())
  {
    return $this->getTable()->getProjectReport($this->getId(), $filters);
  }

  public function getMilestonesProfilesCosts()
  {
    return $this->getTable()->getProjectMilestonesProfilesCosts($this->getId());
  }

  public function getUserCredential(sfGuardUser $user)
  {
    if (! $this->getId() || ! $user->getId())
    {
      return false;
    }

    $credential = ProjectUserTable::getInstance()->findOneByProjectIdAndUserId($this->getId(), $user->getId())->getPermission()->getName();

    return $credential;
  }

  public function getProfiles()
  {
    return $this->getTable()->getProjectProfiles($this->getId());
  }
}
