<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    TimeTracker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function hasProject(Project $project)
  {
    return false !== $this->getProjects()->search($project);
  }

  public function getInputsByDate($date)
  {
    return InputTable::getInstance()->getInputsByUserAndDate($this->getId(), $date);
  }

  public function getInputTimeSpentByDate($date, $excludeInputId)
  {
    return InputTable::getInstance()->getInputTimeSpentByUserAndDate($this->getId(), $date, $excludeInputId);
  }

  public function getInputs()
  {
    return InputTable::getInstance()->getInputsForUser($this->getId());
  }

  public function hasAssignment(Assignment $assignment)
  {
    return $this->getId() === $assignment->getUserId();
  }

  public function getActiveProjects()
  {
    return ProjectTable::getInstance()->getUserActiveProjects($this->getId());
  }
}
