generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Module
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          module
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 0
        display: [ =name ]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
