generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Assignment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          assignment
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        Priority:
          label:
      list:
        table_method: retrieveAssignmentList
        display: [ Priority, Milestone, Module, Task, User, Profile, time_estimated, time_allocated ]
      filter:
        display: [ milestone_id, module_id, profile_id, user_id, is_completed ]
      form:
        actions:
          save: ~
      edit:    ~
      new:     ~
